### ISSUE TITLE
Rueidis adds 44 MB to build binary

### ISSUE THREAD

**Issue by nightwolfz** [redis/rueidis#109]
This eclipses every single other module my project is using combined.

Anything we can do about this?

**Comment by rueian** [comment]
Hi @nightwolfz,

The `internal/cmds` contains the generated command builder. It is indeed very big due to the complexity of the redis command syntax.

However, normally you won't use all its generated code, and therefore the binary size after compilation won't be such big.

For example, the real binary size of the following program is 5.1MB on my laptop while the `goweight` still says that it should be at least 44MB:
```go
package main

import (
	"context"
	"github.com/rueian/rueidis"
)

func main() {
	c, err := rueidis.NewClient(rueidis.ClientOption{})
	if err != nil {
		panic(err)
	}
	c.Do(context.Background(), c.B().FtSearch().Index("").Query("").Build())
}
```

Please also check this https://github.com/jondot/goweight/issues/16

**Comment by rueian** [comment]
Hi @nightwolfz,

Is the size problem still bothering you?

**Comment by shushenghong** [comment]
after import rueidis, the binary size add more than 10MB, and i have used `-ldflags=-w` build flags

## without rueidis
```bash
-rwxr-xr-x   1 shushenghong  staff    29M  3 29 15:42 main
```


## with rueidis
```bash
-rwxr-xr-x   1 shushenghong  staff    38M  3 29 15:40 main
```
<img width="966" alt="image" src="https://user-images.githubusercontent.com/3275714/228462051-eb57f1a6-a57e-4874-aebb-028438dddda4.png">

**Comment by palkan** [comment]
Hey there!

First of all, thanks for library. I've started migrating anycable-go to use ruedis and recently discovered that binary sizes increased by ~8MB (you can see the difference in the [releases](https://github.com/anycable/anycable-go/releases), between 1.3.0 and 1.4.0, I tested locally to confirm it's due to ruedis). I see a similar to above picture when running `go-binsize-treemap`, too:

<img width="268" alt="image" src="https://github.com/redis/rueidis/assets/1516722/f5c4e742-b7bc-4176-a4d8-ce5b0a726840">

I can't say going from 13MB to 21MB is a big concern, but it's noticeable.

> normally you won't use all its generated code, and therefore the binary size after compilation won't be such big.

It doesn't seem that Go so smart to eliminate some of the code loaded from `internal/cmds`; it either all or nothing. I found that the following minimal rueidis usage results in the same binary size increase:

```go
package pubsub

import (
	"sync"
	"github.com/redis/rueidis"
)

type RedisSubscriber struct {
	client        rueidis.Client
	clientOptions *rueidis.ClientOption
	clientMu      sync.RWMutex
}

func NewRedisSubscriber(args ...interface{}) (*RedisSubscriber, error) {
	return &RedisSubscriber{}, nil
}

func (s *RedisSubscriber) initClient() error {
	s.clientMu.Lock()
	defer s.clientMu.Unlock()

	if s.client != nil {
		return nil
	}

	c, err := rueidis.NewClient(*s.clientOptions)

	if err != nil {
		return err
	}

	s.client = c

	return nil
}
```

(Compiled with `-ldflags="-s -w"`, of course)
