### ISSUE TITLE
Readonly command on Replica servers only

### ISSUE THREAD

**Issue by Xanvial** [redis/rueidis#132]
Hello,
I'm currently starting to implement this library on our system. Using default cluster implementation with 3 masters and 3 replicas. One of the main things that I want to implement is using only replica servers for all readonly command. Is this supported in the library? I can't seem to find it in the documentation/code.

Not sure about the implementation, but on goredis this can be enabled by setting up a flag on goredis initialization https://github.com/go-redis/redis/blob/master/cluster.go#L40

**Comment by rueian** [comment]
Hi @Xanvial,

Unfortunately, it doesn’t read from the replicas currently. Would you consider using Client-Side Caching instead?

Reading from replicas might make implementation be extremely complex. Currently, I don’t have idea about how to implement it.

**Comment by Xanvial** [comment]
I see, well I haven't read and deep dive this library yet, but on other like goredis, the rough flow of replica readonly is like this
1. Get cluster slot/shard data
2. Assign list of node as array for each slot, usually master is first index, and the replicas will use the rest (in case there's more than one replica)
3. When there's a request that marked as readonly, it will choose one of the replica of related slot
4. On choosen node, call `READONLY` command (only needed once as long as the connection is not closed)
5. Do the command as usual

Well, like mentioned before, I have no clue how hard it's to implement in here. But this feature can help when there's a high RPS for readonly commands, we can scale the system up just by adding a new replica node so the network traffic can be distributed.

**Comment by rueian** [comment]
Thank you for the detailed procedure. One more thing that also need to be considered is cluster topology migration. Procedures may become more complicated during that period.

In terms of high RPS, I believe client side caching is much better than adding more redis replicas. I would  recommend you try that.

**Comment by Xanvial** [comment]
yes I agree, I also want to try this lib for the client side caching feature. But the readonly feature also helping to split the task, so replicas will only responsible for readonly command, while master node only doing Write command only

**Comment by jashakimov** [comment]
Hi @rueian 
Tell me please, what will happen if we deploy app with client side cache? There are will be deleted?

**Comment by smf8** [comment]
Hello @rueian

I wanted to test the read from replica feature in my **multi-node sentinel Redis** setup (I don't have much experience with Redis cluster). So I'd like to try implementing a solution for `sentinelClient` to support `ReplicaReadOnly` option. It would be great to have feedback on the design.

This option will create a completely different type of client. It won't add a new `conn` field to `sentinelClient`. Just like go-redis, this option will make the client randomly connect to a slave replica and switch to another in case of any failure.

1 - A new field will be added to `ClientOption` called `ReplicaReadOnly`
2 - `ReplicaReadOnly` will be used in `sentinelClient._refresh()` to indicate we want to connect to a **slave replica** instead of master.
3 - Update `listWatch` and other methods to work with slave replicas.
4 - Reject any command with `cmd.IsReadOnly()` in `Do`, `DoCache`, `DoMulti` etc.

Please share your thoughts on this and let me know if I missed anything.

**Comment by rueian** [comment]
Hi @smf8,

Thank you for your contribution. Reading from replicas is much more complex than we might think.

One thing

**Comment by smf8** [comment]
That for sure is true, but I think this option for sentinel setup (not cluster) is much simpler.

**Comment by NeoHuang** [comment]
Hi @rueian. I've tried the client side cache with AWS ElastiCache(cluster mode enabled) and it works great. but meanwhile, I've noticed that all traffic go to the primary node. as a result, primary nodes CPU goes higher than using `go-redis` without client side caching while replicas are mostly idle. with go-redis client I could set [ReadOnly flag](https://github.com/redis/go-redis/blob/c0ab7815ea66b036d0cb02e2902a7820551d948a/cluster.go#L44) so all writes go to primary node and all reads go to replicas. if we can have both readonly from replica and client side caching, it can boost the read throughput quite a lot and more scalable. I see @smf8 has implemented it for sentinel client but is there any plan to implement this in cluster client as well in the near future? thanks in advance

**Comment by rueian** [comment]
Hi @NeoHuang,

I personally have no near plan to implement reading from cluster replicas.

**Comment by NeoHuang** [comment]
@rueian  thanks for your response. I read the source code a bit. if I understood correctly. https://github.com/redis/rueidis/blob/8410f48d401542093ab45261c88d5bd8e3236942/cluster.go#L206-L213 these lines are the key lines to pick the connection for each slot and currently it's always `master` right? so in order to make the code be able to pick replicas we need make `c.slots` be `[16384][]conn` type and only append replica connections into `c.slots` instead when  `ReplicaOnly` flag is true. and when sending the command we can randomly pick a conn from the `[]conn` slice?

**Comment by rueian** [comment]
> @rueian thanks for your response. I read the source code a bit. if I understood correctly:
> 
> https://github.com/redis/rueidis/blob/8410f48d401542093ab45261c88d5bd8e3236942/cluster.go#L206-L213
> 
> these lines are the key lines to pick the connection for each slot and currently it's always `master` right? so in order to make the code be able to pick replicas we need to make `c.slots` be `[16384][]conn` type and only append replica connections into `c.slots` instead of `master` when `ReplicaOnly` flag is true. and when sending the command we can randomly pick a conn from the `[]conn` slice?

Yes, exactly!

**Comment by rueian** [comment]
Addressed by https://github.com/redis/rueidis/pull/346
