### ISSUE TITLE
How to convert Hmget() result to a slice of defined struct?

### ISSUE THREAD

**Issue by piavgh** [redis/rueidis#260]
Hi @rueian ,

I'm trying to use rueidis to replace go-redis (due to this issue https://github.com/redis/go-redis/issues/2046),
But at the moment, there is no documentation on how to convert a `Hmget()` result into a slice of defined struct

For example, I want to get the list of pools data by `Hmget()`, params is the list of pool addresses
```
cmd := r.redisClient.B().Hmget().Key(r.keyPools).Field(addresses...).Build()
	poolDataList, err := r.redisClient.Do(ctx, cmd).ToArray()
	if err != nil {
		return nil, err
	}
```

How to convert `poolDataList` to something like `[]Pool`?
Thanks

**Comment by rueian** [comment]
Hi @piavgh,

There are two options:
1. Using the `.AsStrSlice()` instead of the `.ToArray()` to get a string slice, then you can construct your `[]Pool` from it.
2. Loop over the items of `poolDataList` and invoke `.ToString()` on each of them and check nil value by using `rueidis.IsRedisNil(err)` 

Note that if you use `.AsStrSlice()`, the nil value will be present as an empty string in the string slice.

**Comment by piavgh** [comment]
@rueian : thanks, now I got it
