### ISSUE TITLE
rueidisaside should take preconfigured client

### ISSUE THREAD

**Issue by letientai299** [redis/rueidis#305]
I'm experimenting with `rueidisaside` package. The feature looks promising. However, current exported API design disallow reuse pre-configured client, e.g. reuse debug logger hook.

**Comment by rueian** [comment]
Hi @letientai299,
It is intentionally not to take an preconfigured client. 
Because the implementation relies on the invalidation hook which can’t be set after initiated. 

However, we can have a ClientBuilder function to allow you to inject a custom logger. Just like this https://github.com/redis/rueidis/blob/34c5b924e92ceed66faa604821f6aa0d04dbbe64/rueidislock/lock.go#L27

**Comment by rueian** [comment]
Hi @letientai299,

v1.0.13 is released with the `ClientBuilder ` option!
