### ISSUE TITLE
The function of KeyMajority, why do you need multiple keys, not one

### ISSUE THREAD

**Issue by jeffmingup** [redis/rueidis#414]
May I ask why it is necessary to send multiple keys in lock to satisfy the KeyMajority? I do not see this practice in the distributed-locks article. 
Thank you.  Very good library.

**Comment by rueian** [comment]
Hi @jeffmingup,

Indeed, the [redlock document](https://redis.io/docs/manual/patterns/distributed-locks/) doesn't mention multiple keys but requires a fixed number of many nodes instead.

While, in my opinion, it is impractical that people will prepare many standalone redis nodes to use redlock. Most people will setup Redis Cluster instead. With Redis Cluster, the closest behavior to acquiring a lock on multiple nodes is acquiring multiple keys because those keys will be distributed by the cluster.

That is the reason behind the KeyMajority. If you are using a single redis or for any other reason, you can set this option to 1 to lock on 1 key.

**Comment by jeffmingup** [comment]
Thank you very much for your reply, I understand
