### ISSUE TITLE
Client with RueidisOtel missing in README docs

### ISSUE THREAD

**Issue by DestroyerAlpha** [redis/rueidis#442]
In README for rueidisotel, we have imported Rueidisotel but we are not using the methods from it to initialise client.

**Comment by DestroyerAlpha** [comment]
Also, @rueian when can we expect new release with connection stats?

**Comment by rueian** [comment]
Hi @DestroyerAlpha,

Thank you for catching the error. Would you be willing to correct the README for us as well?

> Also, @rueian when can we expect new release with connection stats?

These four metrics are introduced since v1.0.24:
* rueidis_dial_attempt: number of dial attempts
* rueidis_dial_success: number of successful dials
* rueidis_dial_conns: number of connections
* rueidis_dial_latency: dial latency in seconds


And you have to initialize your client with the rueidisotel.NewClient constructor to instrument them.

**Comment by DestroyerAlpha** [comment]
Can't seem to find the rueidisotel.NewClient in github.com/redis/rueidis v1.0.25-go1.18.

**Comment by rueian** [comment]
> Can't seem to find the rueidisotel.NewClient in github.com/redis/rueidis v1.0.25-go1.18.

Oh, rueidisotel.NewClient uses the latest otel which requires go 1.20, therefore it is not available in the `-go1.18` and `-go1.19` builds.

**Comment by DestroyerAlpha** [comment]
@rueian have raised the PR to fix the documentation issue.

**Comment by rueian** [comment]
> @rueian have raised the PR to fix the documentation issue.

LGTM. Thanks!
