### ISSUE TITLE
Add IsParseError() documentation

### ISSUE THREAD

**Issue by rueian** [redis/rueidis#578]
Since https://github.com/redis/rueidis/pull/555 and https://github.com/redis/rueidis/pull/564, the following statement `Otherwise, it panics.` is no longer correct and should be removed.

https://github.com/redis/rueidis/blob/5fe0175fe338cca5685968b73963e0eb159affb3/README.md?plain=1#L437-L438

Besides the removal, we should make it clear that an `errParse` will be returned if choosing a wrong parser function and the `IsParseErr` helper can be used for checking the case.

**Comment by karimalzalek** [comment]
Hello @rueian , since this is a simple documentation change, will take a chance to contribute my first change.
I read the documentation under [](https://github.com/redis/rueidis/blob/main/README.md#command-response-cheatsheet)

In the PR I will remove `Otherwise, it panics.` and add the info about errParse and IsParseErr
