### ISSUE TITLE
Error updating the cluster architecture

### ISSUE THREAD

**Issue by ajzach** [redis/rueidis#587]
Hello, I am having an issue with one of our clusters (AWS Elasticache) that has autoscaling configured. The cluster has a minimum of 10 and a maximum of 15. During the day, the cluster scaled up to 13 nodes, and the client correctly detected the new nodes. However, it then scaled back down to 10, and we started seeing errors where the client was trying to resolve the domain of the nodes that had been removed, causing errors. I tested adding the 11th node back, and the client detected it, but once I removed it again, the errors reappeared. It seems like the client is not updating the cluster architecture internally. We are using version 1.0.35.

**Comment by rueian** [comment]
Hi @ajzach, did the errors disappear eventually?

**Comment by ajzach** [comment]
> Hi @ajzach, did the errors disappear eventually?

Hello @rueian, no, we saw the errors for hours, they disappeared when I added the nodes back to the cache.

**Comment by proost** [comment]
I also experienced a similar issue. When i scale down nodes in cluster, client doesn't update correctly. currently i digging it now.

**Comment by rueian** [comment]
Hi @ajzach,

I have just tested AWS Elasticache by deleting shards manually, but I didn't see the DNS error you described and rueidis updated the cluster nodes successfully.
<img width="1570" alt="image" src="https://github.com/user-attachments/assets/ba68ca18-8bbe-49f6-9a89-c34e7825eebe">

Additionally, I found the AWS Elasticache responds to the `CLUSTER SHARDS` with IP addresses instead of domain names.
> the client was trying to resolve the domain of the nodes that had been removed, causing errors.

So this looks weird to me. Do you manually put the domain names of nodes into the `rueidis.ClientOption.InitAddress`? In the case of AWS Elasticache, the InitAddress should be just the configuration endpoint provided by AWS.

**Comment by ajzach** [comment]
To connect to Redis, I just use the endpoint. I performed the same tests adding and removing nodes, including failover, and everything worked correctly. This error is not very common; currently, we have more than 100 applications using Rueidis, and only 2 have reported this problem. It seems that the error occurs with more prolonged use of the client. Some condition causes the client to stop updating the cluster architecture internally and to retain in memory nodes that were deleted.

**Comment by rueian** [comment]
Hi @ajzach,

Rueidis sends `CLUSTER SHARDS` to the configuration endpoint to get the latest cluster topology whenever an error occurs or a Redis `MOVED` response is received. Based on your description, the mechanism was still working since those domain name errors disappeared when you added new nodes. So I think it was more likely that your configuration endpoint kept giving you stale topology until a new node was added.

The current rueidis always gets the latest cluster topology from the configuration endpoint only, but it seems not to work well with your Elasticache cluster. Would you like to try the new [v1.0.42-alpha](https://github.com/redis/rueidis/releases/tag/v1.0.42-alpha)? The new version will send `CLUSTER SHARDS` to a known node randomly. I think it will reduce the chance of getting stale information.

**Comment by proost** [comment]
It is hard to reproduce situation. I agree with rueian. i guess that configuration endpoint returns stale cluster information. because i scale in/out, scale up/down clusters sometiems, but this is my first time not to update cluster topology.

**Comment by rueian** [comment]
Thanks @proost! Would you also like to try the [v1.0.42-alpha](https://github.com/redis/rueidis/releases/tag/v1.0.42-alpha)? And how old is your Elasticache cluster? I found that a newly created Elasticache forms the cluster with IP addresses instead of domain names. It is even impossible for me to get a domain name resolution error.

**Comment by proost** [comment]
> how old is your Elasticache cluster

do you mean version of redis or operating time?

**Comment by rueian** [comment]
> @rueian
> 
> > how old is your Elasticache cluster
> 
> do you mean version of redis or operating time?

Maybe both. I think it is possible that clusters have differences even on a same redis version but created on different date.

**Comment by proost** [comment]
@rueian 
I ran the redis cluster about 13 months. About 4weeks ago, i scale down the cluster.

I use redis 7.0.7 version

**Comment by ajzach** [comment]
> Hi @ajzach,
> 
> Rueidis sends `CLUSTER SHARDS` to the configuration endpoint to get the latest cluster topology whenever an error occurs or a Redis `MOVED` response is received. Based on your description, the mechanism was still working since those domain name errors disappeared when you added new nodes. So I think it was more likely that your configuration endpoint kept giving you stale topology until a new node was added.
> 
> The current rueidis always gets the latest cluster topology from the configuration endpoint only, but it seems not to work well with your Elasticache cluster. Would you like to try the new [v1.0.42-alpha](https://github.com/redis/rueidis/releases/tag/v1.0.42-alpha)? The new version will send `CLUSTER SHARDS` to a known node randomly. I think it will reduce the chance of getting stale information.

At the moment I was experiencing errors, I accessed the application instance and queried the nodes directly at the endpoint; the nodes that had been removed were not listed.

**Comment by rueian** [comment]
Hi @ajzach, that was probably because at that time the configuration endpoint resolved to a relatively new node while rueidis kept an old connection to an old node.

**Comment by rueian** [comment]
Hi @ajzach, the [v1.0.42-alpha](https://github.com/redis/rueidis/releases/tag/v1.0.42-alpha) should reduce the chance of getting stale information from an old connection. Please let me know if you have tried it.

**Comment by ajzach** [comment]
I remember that the specialization in the AWS configuration was done for a reason. What are the implications of removing it?

**Comment by rueian** [comment]
The configuration endpoint is essentially a DNS alias to all nodes according to an AWS Redis team member. The specialization was made before I knew that fact and with a wrong assumption that the endpoint was a special program that was responsible for cluster topology. So the specialization is actually meaningless.

**Comment by dangngoctam00** [comment]
Hi @rueian, 
Yesterday, I tested redis cluster failover in `aws`, the topology is 1 shard master node + 2 replicas, there are 2 cases:
+ success
+ failed
in failed case, it was strange behavior based on what I've captured:
- before failover: client send request to replica node, I think it should not be like this, because client is not allowed to read/write to replica node, it should receive `moved` response.
- after failover: client receives `moved` response because previous master node has became replica node, but there is no `cluster shard` command is sent to redis.

I think `rueidis` refreshes connections each time it receives a `moved response`, but currently I do not see it (by usng tcpdump).

I'm using `rueidis v1.0.37`. This phenomenon last about 10 hours and still keep continue. Does it relate to this patch https://github.com/redis/rueidis/releases/tag/v1.0.42-alpha? 
Thank you very much.

**Comment by rueian** [comment]
Hi @dangngoctam00,

That looks very weird. Have you ever seen the cluster shards command been sent after initialization?

**Comment by dangngoctam00** [comment]
Hi @rueian , I've not checked it in failed case, maybe I need to test it again.
About success case, `cluster shards` is sent after failover process.

**Comment by proost** [comment]
@dangngoctam00 could you try again after bump up rueidis version?

**Comment by dangngoctam00** [comment]
Hi @proost , I will upgrade version to `1.0.43` and try again next Monday, I'll reply in this thread.
Anyway, I still want to understand why client got stuck and kept receive `moved` response. 
Thank you!

**Comment by dangngoctam00** [comment]
Hi @rueian , @proost , 
maybe there is a blocking in function `_refresh` of cluster client at line https://github.com/redis/rueidis/blob/b514a567d88619c445c188248bae2515d166b0e4/cluster.go#L220.
When there are multiple connections and there is only 1 aws endpoint, function `getClusterSlots` will be executed only one time, it leads to this line https://github.com/redis/rueidis/blob/b514a567d88619c445c188248bae2515d166b0e4/singleflight.go#L58C2-L58C12 will not be executed, so the following times of `LazyDo` will be ignored. 
Could you review it? Thank you.

**Comment by rueian** [comment]
Hi @dangngoctam00,

Thank you for looking into the details. If that was the case then versions after v1.0.42 should have fixed it.

I also dropped the [v1.0.45-alpha.2](https://github.com/redis/rueidis/releases/tag/v1.0.45-alpha.2) which adds timeout on the 
`getClusterSlots` to avoid it from being stuck. Could you give it a try?

**Comment by dangngoctam00** [comment]
Hi @rueian , I've tried with https://github.com/redis/rueidis/releases/tag/v1.0.45-alpha.2 and client refreshes redis cluster topology normally.
FYI: when testing, I've also found this bug: https://github.com/redis/redis/issues/13414, so I also think it's good to send `cluster shards` randomly to cluster like you said before.
Thank you very much.
