### ISSUE TITLE
Stats for local cache memory usage

### ISSUE THREAD

**Issue by yash-nisar** [redis/rueidis#642]
Is there a way to monitor the local cache memory ? We want to make sure our local cache (server assisted client side cache) doesn't get too many requests and run out of memory.

Thanks !

**Comment by rueian** [comment]
The estimated memory constraint on the client side caching can be adjusted by changing the CacheSizeEachConn option.
https://github.com/redis/rueidis/blob/9ff2841d85658dc5aa29036f217e02e326e95258/rueidis.go#L121

This option along with the PipelineMultiplex option and how many master Redis nodes you have determine the estimated memory limit of all your client side caching. You can reduce either CacheSizeEachConn or PipelineMultiplex to avoid being OOM killed.

These are all estimated because Go does its own memory management and there is no easy way to find the actual memory usage by an object. You can only monitor the actual usage from the operating system.

**Comment by yash-nisar** [comment]
Awesome, thank you so much !
